"""Seed 100 diverse Indian-context support tickets."""
import uuid
from datetime import datetime, timezone, timedelta
import random
from app.database import engine
from app.models.ticket import Ticket, TicketStatus, Priority, Category
from sqlalchemy.orm import Session

AGENT_IDS = [
    "Wh84BCbk1OKPDhqOpLcpNbAEsSEoXLOF",
    "AySoReql4B2l5U7YURo0uHMb4GQptSy4",
    "HkKvrTAQst2WMlq3izEEWk68uMtF6W6E",
]

TICKETS = [
    # Technical / IT — high priority
    {
        "subject": "Cannot access the student portal after password reset",
        "body": "I recently reset my password but I'm still unable to log in to the portal. It keeps showing 'Invalid credentials'. My enrollment number is 2023BCA041. Please help urgently as my assignment submissions are due today.",
        "from_name": "Aarav Sharma",
        "from_email": "aarav.sharma.2023@university.ac.in",
        "status": TicketStatus.open,
        "priority": Priority.high,
        "category": Category.technical_it,
    },
    {
        "subject": "Library e-resources not loading — NPTEL access broken",
        "body": "The NPTEL course links under the library portal are returning a 403 error. I need access for my semester project on Data Structures. Can you check if our institutional access has lapsed?",
        "from_name": "Priya Nair",
        "from_email": "priya.nair@students.niit.ac.in",
        "status": TicketStatus.in_progress,
        "priority": Priority.high,
        "category": Category.technical_it,
    },
    {
        "subject": "Timetable app crashing on Android 14",
        "body": "The official timetable app crashes immediately after the splash screen on my Realme 12 Pro (Android 14). Other students in my batch are facing the same issue. We can't check our exam schedules.",
        "from_name": "Rohan Mehta",
        "from_email": "rohan.mehta@btech2022.edu",
        "status": TicketStatus.open,
        "priority": Priority.high,
        "category": Category.technical_it,
    },
    {
        "subject": "Wi-Fi dropping in hostel block D every evening",
        "body": "Since last Monday the Wi-Fi in Hostel Block D goes completely down between 7 PM and 10 PM. This is the only time we can attend online lectures and submit assignments. Please escalate this to the IT team.",
        "from_name": "Sneha Iyer",
        "from_email": "sneha.iyer.hostel@university.edu",
        "status": TicketStatus.resolved,
        "priority": Priority.high,
        "category": Category.technical_it,
    },
    {
        "subject": "Unable to submit dissertation via the submission portal",
        "body": "I am a final year M.Tech student. The upload button on the dissertation submission portal is greyed out even though the deadline has not passed. My guide has confirmed the topic approval is done. Roll no: MT2024007.",
        "from_name": "Karthik Subramanian",
        "from_email": "karthik.s@mtech2024.ac.in",
        "status": TicketStatus.in_progress,
        "priority": Priority.high,
        "category": Category.technical_it,
    },
    {
        "subject": "Two-factor authentication code not arriving on registered mobile",
        "body": "I registered my Jio number for 2FA but OTPs stopped arriving three days ago. I tried re-registering but the portal says my number is already linked. Now I'm completely locked out.",
        "from_name": "Divya Pillai",
        "from_email": "divya.pillai2022@college.edu.in",
        "status": TicketStatus.open,
        "priority": Priority.high,
        "category": Category.technical_it,
    },
    {
        "subject": "Projector in lecture hall 3B not working for a week",
        "body": "The projector in LH-3B has been non-functional since 12th June. Faculty are struggling to conduct classes. Three complaints have been lodged at the reception desk with no response.",
        "from_name": "Ananya Krishnamurthy",
        "from_email": "ananya.k@faculty.university.ac.in",
        "status": TicketStatus.resolved,
        "priority": Priority.medium,
        "category": Category.technical_it,
    },
    {
        "subject": "VPN access not working for off-campus research database",
        "body": "I'm a PhD scholar working from home. The institutional VPN I use to access IEEE Xplore and Springer Link stopped authenticating after the June 10th system update. Other scholars in my lab report the same.",
        "from_name": "Rajesh Venkataraman",
        "from_email": "rajesh.v.phd@research.iitx.ac.in",
        "status": TicketStatus.in_progress,
        "priority": Priority.medium,
        "category": Category.technical_it,
    },
    {
        "subject": "Email quota exceeded — cannot receive any new emails",
        "body": "My university email account has hit its storage quota. I've tried deleting old emails but the webmail client is very slow. I urgently need to receive an offer letter from an internship company. Can the quota be increased or old emails archived?",
        "from_name": "Pooja Agarwal",
        "from_email": "pooja.agarwal@bca2021.edu.in",
        "status": TicketStatus.open,
        "priority": Priority.medium,
        "category": Category.technical_it,
    },
    {
        "subject": "Lab computers missing Python 3.11 — only 2.7 installed",
        "body": "CS Lab 2 computers only have Python 2.7 installed. Our syllabus requires Python 3.11. The practical exam is on Friday. Can IT please update the lab machines?",
        "from_name": "Vikram Gupta",
        "from_email": "vikram.gupta.cs3@university.ac.in",
        "status": TicketStatus.resolved,
        "priority": Priority.high,
        "category": Category.technical_it,
    },
    {
        "subject": "Student ID card not scanning at library gate",
        "body": "My new ID card (issued last week) doesn't scan at the library entry scanner. The security guard is manually logging me in but this causes delays. Student ID: 2024BCE129.",
        "from_name": "Ishaan Bose",
        "from_email": "ishaan.bose@btech2024.ac.in",
        "status": TicketStatus.open,
        "priority": Priority.low,
        "category": Category.technical_it,
    },
    {
        "subject": "Online exam proctoring software not compatible with MacBook M3",
        "body": "ProctorU is not launching on my MacBook Air M3. It shows 'Unsupported hardware' and the exam is tomorrow at 10 AM IST. Please advise on how to proceed. I cannot borrow a Windows machine on such short notice.",
        "from_name": "Meera Ramachandran",
        "from_email": "meera.r.mca@college.edu",
        "status": TicketStatus.resolved,
        "priority": Priority.high,
        "category": Category.technical_it,
    },
    {
        "subject": "Hostel room allocation portal showing wrong room number",
        "body": "The portal shows me in Room 214 but I was physically allotted Room 307 by the hostel warden. I need the portal corrected before I apply for the mess facility linked to my room number.",
        "from_name": "Arjun Patel",
        "from_email": "arjun.patel.hostel@university.edu.in",
        "status": TicketStatus.open,
        "priority": Priority.medium,
        "category": Category.technical_it,
    },
    {
        "subject": "SWAYAM integration not reflecting completed courses",
        "body": "I completed two SWAYAM courses (Data Science and Cloud Computing) but they do not appear in my academic record on the university portal. I have the completion certificates. How do I get credit for them?",
        "from_name": "Lavanya Srinivasan",
        "from_email": "lavanya.s@msc2023.university.ac.in",
        "status": TicketStatus.in_progress,
        "priority": Priority.medium,
        "category": Category.technical_it,
    },
    {
        "subject": "Zoom link for online classes not working for entire section",
        "body": "The recurring Zoom link for Section B (MBA Sem 3 — Marketing) expired. Roughly 60 students missed the morning session today. Please regenerate the link and share it on the portal notice board.",
        "from_name": "Tanvi Deshpande",
        "from_email": "tanvi.deshpande.mba3b@bschool.ac.in",
        "status": TicketStatus.resolved,
        "priority": Priority.high,
        "category": Category.technical_it,
    },

    # Billing / Fees — high priority
    {
        "subject": "Scholarship amount not credited for April–June quarter",
        "body": "I am a merit scholarship holder (SC category). The stipend for April–June 2025 has not been credited to my bank account even though the disbursement date was May 30th. My scholarship ID is SCH2023-0481. Please check the status.",
        "from_name": "Deepak Jadhav",
        "from_email": "deepak.jadhav@btech2022.government.ac.in",
        "status": TicketStatus.open,
        "priority": Priority.high,
        "category": Category.billing_fees,
    },
    {
        "subject": "Double deduction of hostel fees from my account",
        "body": "My bank account was debited twice for the Semester 2 hostel fees on June 5th — ₹42,000 each time. I have attached my bank statement. Please refund the extra deduction. Transaction IDs: TXN20250605-8821 and TXN20250605-8822.",
        "from_name": "Sunita Yadav",
        "from_email": "sunita.yadav@mba2024.ac.in",
        "status": TicketStatus.in_progress,
        "priority": Priority.high,
        "category": Category.billing_fees,
    },
    {
        "subject": "Fee payment portal not accepting UPI — only NEFT working",
        "body": "The fee portal's UPI option (using BHIM, GPay, PhonePe) returns 'Payment Gateway Timeout' for the last 3 days. I need to pay the semester fee before the June 25th deadline to avoid a fine. Please fix urgently.",
        "from_name": "Nikhil Joshi",
        "from_email": "nikhil.joshi.bca3@college.edu.in",
        "status": TicketStatus.open,
        "priority": Priority.high,
        "category": Category.billing_fees,
    },
    {
        "subject": "HDFC education loan NOC not being issued by accounts office",
        "body": "HDFC Bank is requesting an NOC from the university confirming I have no outstanding dues before releasing my loan disbursement. The accounts office says it takes 10 working days but it has been 18 days. My admission deadline at the target university is July 1st.",
        "from_name": "Preethi Venkatesh",
        "from_email": "preethi.v.mba@bschool.edu.in",
        "status": TicketStatus.in_progress,
        "priority": Priority.high,
        "category": Category.billing_fees,
    },
    {
        "subject": "Late fee charged despite on-time payment",
        "body": "I paid my tuition fee on June 14th (deadline June 15th) via Net Banking. The receipt is attached. However, my account statement shows a late fee of ₹1,500 applied on June 16th. Please waive this and update my account.",
        "from_name": "Sahil Kapoor",
        "from_email": "sahil.kapoor@bsc2023.university.ac.in",
        "status": TicketStatus.resolved,
        "priority": Priority.high,
        "category": Category.billing_fees,
    },
    {
        "subject": "Wrong amount shown on fee structure — mismatch with admission letter",
        "body": "My admission letter states the annual fee as ₹1,20,000 but the fee portal shows ₹1,45,000. I am from Rajasthan and applied under the state quota which carries a fee waiver. Please reconcile this before the payment deadline.",
        "from_name": "Rekha Choudhary",
        "from_email": "rekha.c.mca2024@university.ac.in",
        "status": TicketStatus.open,
        "priority": Priority.high,
        "category": Category.billing_fees,
    },
    {
        "subject": "NSP scholarship verification pending for 45 days",
        "body": "I applied for the National Scholarship Portal (NSP) scholarship in April. The university verification step has been pending for 45 days. The deadline for institute verification on the NSP portal is June 30th. Can you please expedite?",
        "from_name": "Govind Pawar",
        "from_email": "govind.pawar.obc@btech2023.ac.in",
        "status": TicketStatus.open,
        "priority": Priority.high,
        "category": Category.billing_fees,
    },
    {
        "subject": "Alumni dues showing as pending on transcript despite clearance",
        "body": "I cleared all my dues in March 2025 and received a clearance certificate. But when I requested my final transcript, it was held citing 'pending alumni dues of ₹500'. I need the transcript for my visa application to Germany next week.",
        "from_name": "Amit Kumar Singh",
        "from_email": "amit.singh.alumni2025@university.ac.in",
        "status": TicketStatus.resolved,
        "priority": Priority.high,
        "category": Category.billing_fees,
    },
    {
        "subject": "Sports fee charged for a student who opted out",
        "body": "I submitted the sports fee opt-out form in August 2024 (attached). Despite this, ₹3,000 has been added to my fee statement for Semester 3. Please remove this charge and confirm via email.",
        "from_name": "Chandrika Mohan",
        "from_email": "chandrika.m@bsc2023.college.edu",
        "status": TicketStatus.in_progress,
        "priority": Priority.medium,
        "category": Category.billing_fees,
    },
    {
        "subject": "Mess fee deducted for months when I was on internship leave",
        "body": "I was on approved internship leave from January 15th to April 30th 2025 and not using the mess facility. However, the full mess fee (₹8,400/month) was deducted for all three months. I have the internship approval letter. Please refund.",
        "from_name": "Harish Pandey",
        "from_email": "harish.pandey.btech4@university.ac.in",
        "status": TicketStatus.open,
        "priority": Priority.medium,
        "category": Category.billing_fees,
    },
    {
        "subject": "Fee receipt not generated after successful payment",
        "body": "I paid ₹65,000 via SBI Net Banking (Ref: SBI2506180093) two days ago. The money was deducted from my account but the portal still shows 'Payment Pending' and no receipt was generated. I need the receipt for income tax purposes.",
        "from_name": "Shreya Tiwari",
        "from_email": "shreya.tiwari.mba2@bschool.ac.in",
        "status": TicketStatus.resolved,
        "priority": Priority.medium,
        "category": Category.billing_fees,
    },
    {
        "subject": "SC/ST fee concession not applied to my account",
        "body": "I belong to the SC category and submitted all required documents (caste certificate, income certificate) during admission. The concession should be 100% on tuition but full fees were charged. Admission number: 2024BCA-SC-019.",
        "from_name": "Sanjay Kamble",
        "from_email": "sanjay.kamble.bca@college.edu.in",
        "status": TicketStatus.in_progress,
        "priority": Priority.high,
        "category": Category.billing_fees,
    },
    {
        "subject": "Demand draft not accepted — bank says college account is inactive",
        "body": "I went to SBI today to submit a demand draft for the exam fee. The bank informed me that the university's account number provided on the fee challan may be inactive. Other students are facing the same issue. Please verify the account details.",
        "from_name": "Ritu Bhatt",
        "from_email": "ritu.bhatt.msc2@university.ac.in",
        "status": TicketStatus.open,
        "priority": Priority.high,
        "category": Category.billing_fees,
    },

    # Other — varied
    {
        "subject": "Requesting transfer certificate to join NIT Trichy",
        "body": "I have secured admission at NIT Trichy under DASA scheme and need to submit a Transfer Certificate within 7 days. Kindly expedite the process. I have already submitted the migration form to the registrar's office.",
        "from_name": "Aditya Nambiar",
        "from_email": "aditya.nambiar.2022@university.edu.in",
        "status": TicketStatus.in_progress,
        "priority": Priority.high,
        "category": Category.other,
    },
    {
        "subject": "Bonafide certificate needed for railway concession",
        "body": "I need a bonafide certificate to apply for a student railway concession pass for the Pune–Mumbai route. Please let me know the procedure and expected turnaround time.",
        "from_name": "Kalyani Kulkarni",
        "from_email": "kalyani.k.bcom3@college.ac.in",
        "status": TicketStatus.resolved,
        "priority": Priority.low,
        "category": Category.other,
    },
    {
        "subject": "Internship completion certificate not verified by university",
        "body": "I completed a 6-month internship at Infosys (Bangalore). The HR team has sent the completion certificate directly to the university email but the academic office says they haven't received it. I need it for my final year project credit.",
        "from_name": "Rahul Mishra",
        "from_email": "rahul.mishra.it4@university.ac.in",
        "status": TicketStatus.open,
        "priority": Priority.medium,
        "category": Category.other,
    },
    {
        "subject": "Requesting change of elective from Cyber Security to AI/ML",
        "body": "I registered for Cyber Security as my open elective but the class timings clash with my core subject Lab (CS-401L). I would like to switch to AI/ML. There are still 12 seats available in AI/ML. Please approve the change.",
        "from_name": "Nandini Reddy",
        "from_email": "nandini.reddy.cs3@university.ac.in",
        "status": TicketStatus.resolved,
        "priority": Priority.medium,
        "category": Category.other,
    },
    {
        "subject": "Medical leave not reflected in attendance — below 75%",
        "body": "I was hospitalised at Apollo Hospital, Hyderabad from May 3–18 (doctor's certificate attached). My attendance is showing 68% due to these absences. As per the attendance policy, medical leave should be condoned. Please update my attendance record.",
        "from_name": "Suresh Babu Reddy",
        "from_email": "suresh.reddy.ece3@university.ac.in",
        "status": TicketStatus.in_progress,
        "priority": Priority.high,
        "category": Category.other,
    },
    {
        "subject": "Name mismatch between Aadhaar and university records",
        "body": "My Aadhaar card reads 'Mohd. Imran Khan' but the university records show 'Mohammad Imran Khan'. This mismatch is causing issues in the NSP scholarship application. Please correct the name in university records to match Aadhaar.",
        "from_name": "Mohd. Imran Khan",
        "from_email": "imran.khan.bba2@college.edu.in",
        "status": TicketStatus.open,
        "priority": Priority.medium,
        "category": Category.other,
    },
    {
        "subject": "Sports captain certificate needed for job application",
        "body": "I was captain of the university cricket team in 2022–23. I need an official certificate from the sports department for my campus placement form at TCS. The sports department is asking for a request from the academic office.",
        "from_name": "Yash Dhawan",
        "from_email": "yash.dhawan.mba3@bschool.ac.in",
        "status": TicketStatus.resolved,
        "priority": Priority.low,
        "category": Category.other,
    },
    {
        "subject": "Grievance against unfair internal assessment marks",
        "body": "I received 8/25 in Internal Assessment 2 for MA-201 (Discrete Mathematics). My test paper shows correct solutions for all 4 questions. I have photographic evidence. I request re-evaluation as per the grievance policy.",
        "from_name": "Pallavi Jain",
        "from_email": "pallavi.jain.mca2@university.ac.in",
        "status": TicketStatus.in_progress,
        "priority": Priority.medium,
        "category": Category.other,
    },
    {
        "subject": "Hostel room change request due to health reasons",
        "body": "I have been prescribed to avoid climbing stairs due to a knee injury (doctor's note attached). I'm currently on the 4th floor of the hostel with no lift access. I request a ground floor room. Any block is acceptable.",
        "from_name": "Bhavana Shetty",
        "from_email": "bhavana.shetty.bsc3@college.edu",
        "status": TicketStatus.open,
        "priority": Priority.medium,
        "category": Category.other,
    },
    {
        "subject": "Placement registration portal rejecting my CGPA",
        "body": "The placement registration portal is rejecting my CGPA of 7.8 saying 'minimum CGPA requirement not met'. The minimum as per the placement office is 7.5. My official transcript confirms 7.83. Is there a data entry error in the portal?",
        "from_name": "Kunal Thakur",
        "from_email": "kunal.thakur.it3@university.ac.in",
        "status": TicketStatus.resolved,
        "priority": Priority.high,
        "category": Category.other,
    },
    {
        "subject": "No AC in girls' hostel computer lab during exam prep season",
        "body": "The air conditioning in the girls' hostel computer lab (Block G, Ground Floor) has been non-functional for 2 weeks. With temperatures touching 42°C in Nagpur, studying is impossible after 11 AM. This is a health hazard.",
        "from_name": "Madhuri Wankhede",
        "from_email": "madhuri.w.bca2@college.ac.in",
        "status": TicketStatus.in_progress,
        "priority": Priority.high,
        "category": Category.other,
    },
    {
        "subject": "Request to appear in backlog exam while on semester leave",
        "body": "I have one backlog in DBMS (CS-305) from Semester 5. I am currently on semester break for a startup incubation programme approved by the dean. I request permission to appear in the backlog exam in July without resuming the semester.",
        "from_name": "Farhan Qureshi",
        "from_email": "farhan.qureshi.cs5@university.ac.in",
        "status": TicketStatus.open,
        "priority": Priority.medium,
        "category": Category.other,
    },
    # More technical
    {
        "subject": "Student email account hacked — requesting password force-reset",
        "body": "My university email was compromised. I received a Google security alert about sign-in from an unknown location in Bengaluru. I have already changed my personal Gmail password. Please force-reset my university email and check for unusual activity.",
        "from_name": "Varun Malhotra",
        "from_email": "varun.malhotra.bba3@bschool.ac.in",
        "status": TicketStatus.resolved,
        "priority": Priority.high,
        "category": Category.technical_it,
    },
    {
        "subject": "Online quiz platform auto-submitted before time was up",
        "body": "During the CS-401 quiz today, the online platform auto-submitted my test at 31 minutes even though we had 45 minutes. I had only answered 12 of 20 questions. This happened to 3 other students in my batch as well. Please let us retake.",
        "from_name": "Shweta Soni",
        "from_email": "shweta.soni.cs4@university.ac.in",
        "status": TicketStatus.in_progress,
        "priority": Priority.high,
        "category": Category.technical_it,
    },
    {
        "subject": "Attendance portal marking me absent despite physical presence",
        "body": "The biometric attendance system in Building C (Room 204) is not capturing my fingerprint. The system accepted my fingerprint on the first day but has been rejecting it since. The faculty are manually marking me present but the portal is not updating.",
        "from_name": "Ganesh Patil",
        "from_email": "ganesh.patil.mech2@university.ac.in",
        "status": TicketStatus.open,
        "priority": Priority.medium,
        "category": Category.technical_it,
    },
    {
        "subject": "Moodle server down — cannot access study material before tomorrow's exam",
        "body": "The Moodle LMS has been down since 9 PM today. My exam is at 9 AM tomorrow and all notes and previous year papers are uploaded there. Is there an alternative link or mirror? Please post an update on the student portal.",
        "from_name": "Swati Desai",
        "from_email": "swati.desai.mba2@bschool.edu.in",
        "status": TicketStatus.resolved,
        "priority": Priority.high,
        "category": Category.technical_it,
    },
    {
        "subject": "CCTV footage request for lost laptop in lab",
        "body": "My Dell laptop was left in CS Lab 1 on June 18th between 2–4 PM. When I returned, it was missing. I've filed a police complaint (FIR attached). Please share the CCTV footage of that time window with the police as requested.",
        "from_name": "Akash Tomar",
        "from_email": "akash.tomar.cs3@university.ac.in",
        "status": TicketStatus.in_progress,
        "priority": Priority.medium,
        "category": Category.technical_it,
    },
    {
        "subject": "Digital library login failing with 'subscription expired' error",
        "body": "I'm getting 'Institutional subscription expired' when trying to access JSTOR through the digital library portal. I use this for my research on microfinance. Please renew the subscription or provide a workaround.",
        "from_name": "Rupali Ghosh",
        "from_email": "rupali.ghosh.ma2@arts.university.ac.in",
        "status": TicketStatus.open,
        "priority": Priority.low,
        "category": Category.technical_it,
    },
    {
        "subject": "Printer in administrative block not accessible to students",
        "body": "The student printing kiosk near the admin block has had an 'Out of Order' notice for the past 3 weeks. The nearest alternative is in the library, a 15-minute walk. With 120 students printing project reports this week, the library printer has a 2-hour queue.",
        "from_name": "Nitin Agrawal",
        "from_email": "nitin.agrawal.bca3@college.edu.in",
        "status": TicketStatus.resolved,
        "priority": Priority.low,
        "category": Category.technical_it,
    },
    # More billing
    {
        "subject": "Exam fee paid online but hall ticket not generated",
        "body": "I paid ₹1,800 for the end-semester exam fee on June 16th via the fee portal (Payment Ref: EXAM-25-0619-4471). The hall ticket should auto-generate within 24 hours but it's been 4 days. The exam starts June 23rd.",
        "from_name": "Ramya Krishnan",
        "from_email": "ramya.k.msc3@university.ac.in",
        "status": TicketStatus.open,
        "priority": Priority.high,
        "category": Category.billing_fees,
    },
    {
        "subject": "Requesting fee deferral — father hospitalised",
        "body": "My father was admitted to AIIMS, New Delhi for cardiac surgery on June 10th. We are undergoing significant financial hardship. I request a 60-day deferral on my semester fee with a commitment to pay once he recovers. Hospital documents enclosed.",
        "from_name": "Manish Tripathi",
        "from_email": "manish.tripathi.btech3@university.ac.in",
        "status": TicketStatus.in_progress,
        "priority": Priority.high,
        "category": Category.billing_fees,
    },
    {
        "subject": "Incorrect GSTIN on fee invoice for employer reimbursement",
        "body": "I am a working professional in the evening MBA programme. My employer reimburses tuition fees but requires a GST invoice with the university's correct GSTIN. The invoice generated shows an old GSTIN (pre-GST migration). Please reissue with the correct number.",
        "from_name": "Jaya Balachandran",
        "from_email": "jaya.b.emba2@bschool.ac.in",
        "status": TicketStatus.resolved,
        "priority": Priority.medium,
        "category": Category.billing_fees,
    },
    {
        "subject": "Mess bill showing 31 days in February",
        "body": "My February 2025 mess bill shows charges for 31 days. February had 28 days this year. I am being overcharged for 3 days (₹ 450 at ₹150/day). Kindly correct the bill and adjust the next month's payment.",
        "from_name": "Tejas Kulkarni",
        "from_email": "tejas.k.civil3@university.ac.in",
        "status": TicketStatus.resolved,
        "priority": Priority.low,
        "category": Category.billing_fees,
    },
    {
        "subject": "Pending bus pass renewal for APSRTC student concession",
        "body": "My APSRTC student bus pass expired on May 31st. I submitted the renewal form with college ID and fee receipt on June 2nd. The pass has not been renewed. I am spending ₹60/day on auto-rickshaws in the meanwhile.",
        "from_name": "Padmaja Naidu",
        "from_email": "padmaja.n.bpharm3@pharma.ac.in",
        "status": TicketStatus.open,
        "priority": Priority.medium,
        "category": Category.billing_fees,
    },
    # More Other
    {
        "subject": "Permission for off-campus industry visit — Tata Steel Jamshedpur",
        "body": "The Metallurgy department has organised a 3-day industry visit to Tata Steel, Jamshedpur from July 10–12. We need official permission letters on university letterhead for 35 students. The faculty coordinator is Prof. A. K. Sinha.",
        "from_name": "Prashant Gaikwad",
        "from_email": "prashant.g.meta4@university.ac.in",
        "status": TicketStatus.in_progress,
        "priority": Priority.medium,
        "category": Category.other,
    },
    {
        "subject": "Requesting duplicate marksheet — original lost during house shifting",
        "body": "My Semester 4 original marksheet was lost during house relocation. I have filed a police complaint (attached). Please issue a certified duplicate copy. I need it for a job application at Wipro next week.",
        "from_name": "Savita More",
        "from_email": "savita.more.bsc4@college.edu.in",
        "status": TicketStatus.open,
        "priority": Priority.high,
        "category": Category.other,
    },
    {
        "subject": "Research paper submission — requesting approval for co-authorship with industry mentor",
        "body": "I have co-authored a paper with my external industry mentor (Dr. Ramesh Iyer, ISRO) titled 'Thermal Analysis of CubeSat Structures'. The journal requires a co-authorship approval letter from my university. Please issue one on letterhead.",
        "from_name": "Nivedita Sharma",
        "from_email": "nivedita.s.aerospace4@iit-like.ac.in",
        "status": TicketStatus.resolved,
        "priority": Priority.medium,
        "category": Category.other,
    },
    {
        "subject": "Gate pass needed for equipment loan (oscilloscope) to project lab",
        "body": "I need to borrow an oscilloscope from the main electronics lab and take it to the project lab in Block B for my final year project. I need a signed gate pass from the lab technician. Who do I contact?",
        "from_name": "Abhishek Nair",
        "from_email": "abhishek.n.ece4@university.ac.in",
        "status": TicketStatus.resolved,
        "priority": Priority.low,
        "category": Category.other,
    },
    {
        "subject": "Complaint regarding ragging incident in first year hostel",
        "body": "I wish to report an incident of ragging by third-year students in Hostel Block A on June 17th at approximately 11 PM. I am reporting anonymously for now but can provide details in person. Please acknowledge receipt of this complaint.",
        "from_name": "Anonymous Student",
        "from_email": "confidential.report2025@student.university.ac.in",
        "status": TicketStatus.in_progress,
        "priority": Priority.high,
        "category": Category.other,
    },
    {
        "subject": "Requesting NOC for appearing in UPSC CSE 2025",
        "body": "I am a final year B.Tech student and have cleared the UPSC CSE Prelims. The UPSC requires a NOC from the university confirming I am in my final year and on track to graduate in May 2026. Please issue this at the earliest.",
        "from_name": "Devendra Singh Rawat",
        "from_email": "devendra.rawat.civil4@university.ac.in",
        "status": TicketStatus.open,
        "priority": Priority.high,
        "category": Category.other,
    },
    {
        "subject": "Feedback: Canteen food quality has deteriorated",
        "body": "Over the last month the quality of food in the main canteen has significantly deteriorated. Stale rice was served on June 14th and 17th. Multiple students reported stomach aches. We request an inspection of the canteen contractor's practices.",
        "from_name": "Sundar Rajan",
        "from_email": "sundar.rajan.ece2@university.ac.in",
        "status": TicketStatus.resolved,
        "priority": Priority.low,
        "category": Category.other,
    },
    {
        "subject": "Cultural fest participation certificate not received",
        "body": "I participated in Technoxian 2024 (our annual tech fest) as a robotics event volunteer and coordinator. The certificate was promised by the cultural committee by end of January but it is now June. I need it for my resume.",
        "from_name": "Himanshu Bajpai",
        "from_email": "himanshu.b.cs3@university.ac.in",
        "status": TicketStatus.open,
        "priority": Priority.low,
        "category": Category.other,
    },
    {
        "subject": "Change of permanent address in university records",
        "body": "I have moved from Lucknow to Pune permanently. I need to update my home address in university records for the convocation certificate, which should show my current address. KYC documents for new address are attached.",
        "from_name": "Sunaina Verma",
        "from_email": "sunaina.verma.mba4@bschool.ac.in",
        "status": TicketStatus.in_progress,
        "priority": Priority.low,
        "category": Category.other,
    },
    # More diverse tickets to reach 100
    {
        "subject": "Practical marks not uploaded for BIO-301 despite submission",
        "body": "Our practical viva for Biotechnology BIO-301 was conducted on May 28th. It is now June 20th and the marks have still not been uploaded to the portal. The external examiner confirmed she submitted the mark sheet. 24 students are affected.",
        "from_name": "Apoorva Venkataraman",
        "from_email": "apoorva.v.biotech3@university.ac.in",
        "status": TicketStatus.open,
        "priority": Priority.high,
        "category": Category.other,
    },
    {
        "subject": "Login error on placement cell portal — profile incomplete flag",
        "body": "The placement cell portal marks my profile as 'Incomplete' even though all fields are filled. The 'Submit Profile' button does not respond. The first placement drive is in two weeks. Screenshot attached.",
        "from_name": "Rohit Bansal",
        "from_email": "rohit.bansal.cs4@university.ac.in",
        "status": TicketStatus.in_progress,
        "priority": Priority.high,
        "category": Category.technical_it,
    },
    {
        "subject": "Internet bandwidth insufficient for streaming practical demos",
        "body": "The IT lab internet connection is severely throttled during peak hours (10 AM–1 PM). Live demos during IoT practical sessions buffer constantly. The ISP contract mentions 100 Mbps dedicated. Can the bandwidth be checked?",
        "from_name": "Geeta Dubey",
        "from_email": "geeta.dubey.it3@university.ac.in",
        "status": TicketStatus.resolved,
        "priority": Priority.medium,
        "category": Category.technical_it,
    },
    {
        "subject": "SC/ST certificate uploaded but not verified by admin",
        "body": "I uploaded my SC certificate (issued by Maharashtra government) 3 weeks ago on the scholarship portal. The status still shows 'Under Review'. The last date to submit the verified form to the state government is June 28th.",
        "from_name": "Vinod Dhangare",
        "from_email": "vinod.dhangare.btech2@university.ac.in",
        "status": TicketStatus.in_progress,
        "priority": Priority.high,
        "category": Category.billing_fees,
    },
    {
        "subject": "Requesting extension for project report submission",
        "body": "I was diagnosed with dengue fever on June 10th and hospitalised for 8 days (discharge summary attached). My project report was due June 18th. I request a 2-week extension to June 30th as I am still recovering.",
        "from_name": "Keerthi Ravi",
        "from_email": "keerthi.ravi.mca4@university.ac.in",
        "status": TicketStatus.resolved,
        "priority": Priority.medium,
        "category": Category.other,
    },
    {
        "subject": "UG to PG migration form not available on the portal",
        "body": "I want to continue to the integrated M.Sc. programme after completing my B.Sc. 3rd year. The 'Migration Form' link on the portal returns a 404 error. Has the form been moved? What is the deadline?",
        "from_name": "Smita Patankar",
        "from_email": "smita.patankar.bsc3@university.ac.in",
        "status": TicketStatus.open,
        "priority": Priority.medium,
        "category": Category.technical_it,
    },
    {
        "subject": "Water cooler in EEE block broken — heatwave conditions",
        "body": "The water cooler on the 2nd floor of the EEE block has been broken for 10 days. With temperatures exceeding 43°C, students are purchasing water bottles daily. Please repair or replace the cooler immediately.",
        "from_name": "Saravanan Murugan",
        "from_email": "saravanan.m.eee2@university.ac.in",
        "status": TicketStatus.resolved,
        "priority": Priority.medium,
        "category": Category.other,
    },
    {
        "subject": "Fee waiver for economically weaker section not applied",
        "body": "I hold an EWS certificate from the Sub-Divisional Officer, Patna. The fee waiver for EWS students was announced by the management in February. It has not been reflected in my fee dues. Admission no: 2023EWS-MBA-007.",
        "from_name": "Vivek Kumar",
        "from_email": "vivek.kumar.mba2@bschool.ac.in",
        "status": TicketStatus.open,
        "priority": Priority.high,
        "category": Category.billing_fees,
    },
    {
        "subject": "Hostel Wi-Fi password reset needed — locked out",
        "body": "I changed my hostel Wi-Fi password via the portal 3 days ago but now I can't remember it and the 'Forgot Password' link says 'Service Unavailable'. I work night-shift remotely and desperately need the connection.",
        "from_name": "Pradeep Sinha",
        "from_email": "pradeep.sinha.mca2@college.edu.in",
        "status": TicketStatus.resolved,
        "priority": Priority.low,
        "category": Category.technical_it,
    },
    {
        "subject": "Convocation registration portal closed before I could register",
        "body": "The convocation registration portal closed on June 10th. I was abroad on a research exchange programme and unable to register. I return on June 22nd. Is there any provision to register late and receive my degree at the convocation on July 5th?",
        "from_name": "Preeti Subramaniam",
        "from_email": "preeti.s.mtech4@university.ac.in",
        "status": TicketStatus.in_progress,
        "priority": Priority.high,
        "category": Category.other,
    },
    {
        "subject": "Internal marks not visible for 3 subjects in Sem 5",
        "body": "My internal marks for CS-501, CS-503, and CS-507 are not visible on the portal. For all other subjects they are visible. Exam registration is coming up and I cannot assess if I am at risk.",
        "from_name": "Dinesh Babu",
        "from_email": "dinesh.babu.cs5@university.ac.in",
        "status": TicketStatus.open,
        "priority": Priority.medium,
        "category": Category.technical_it,
    },
    {
        "subject": "Institute ID required for GitHub Student Developer Pack",
        "body": "I'm trying to apply for the GitHub Student Developer Pack which requires a .edu email or official institute ID. My institute email ends in .ac.in, not .edu. GitHub is not accepting it. Can you issue a letter on letterhead confirming I am a current student?",
        "from_name": "Ankit Pandey",
        "from_email": "ankit.pandey.cs3@college.ac.in",
        "status": TicketStatus.resolved,
        "priority": Priority.low,
        "category": Category.other,
    },
    {
        "subject": "Anti-virus software license expired on all lab computers",
        "body": "The Kaspersky license on all CS Lab computers expired last month. The machines now show security warnings at startup which confuse students. Additionally, a USB drive student plugged in last week may have introduced malware.",
        "from_name": "Nalini Rajendran",
        "from_email": "nalini.r.it.lab@university.ac.in",
        "status": TicketStatus.in_progress,
        "priority": Priority.high,
        "category": Category.technical_it,
    },
    {
        "subject": "Requesting permission to start a new student chapter — IEEE",
        "body": "A group of 25 students wishes to form the IEEE Student Chapter at our campus. We have a faculty advisor (Prof. Sunitha Rao, ECE department) and 25+ signed member forms. Please guide us on the approval process.",
        "from_name": "Sriram Balakrishnan",
        "from_email": "sriram.b.ece3@university.ac.in",
        "status": TicketStatus.resolved,
        "priority": Priority.low,
        "category": Category.other,
    },
    {
        "subject": "Laptop repair charges not reimbursed from student welfare fund",
        "body": "I applied for reimbursement from the Student Welfare Fund for laptop repairs (₹8,500) caused by a power surge in the hostel. The application was approved in March. The amount has not been credited 3 months later.",
        "from_name": "Anjali Singh",
        "from_email": "anjali.singh.mba3@bschool.ac.in",
        "status": TicketStatus.open,
        "priority": Priority.medium,
        "category": Category.billing_fees,
    },
    {
        "subject": "ERP portal login not working after semester re-registration",
        "body": "After completing semester re-registration I cannot log in to the ERP portal. It says 'Student record not found for current semester'. My fee is paid and registration was confirmed by the system.",
        "from_name": "Harshad Kothari",
        "from_email": "harshad.k.commerce3@university.ac.in",
        "status": TicketStatus.in_progress,
        "priority": Priority.high,
        "category": Category.technical_it,
    },
    {
        "subject": "Requesting change of course mentor — communication issues",
        "body": "I have been trying to reach my assigned course mentor, Prof. B. Sharma, for 6 weeks via email and office hours with no response. I have project decisions pending. I request assignment to another available mentor in the department.",
        "from_name": "Ankita Tiwari",
        "from_email": "ankita.tiwari.msc2@university.ac.in",
        "status": TicketStatus.open,
        "priority": Priority.medium,
        "category": Category.other,
    },
    {
        "subject": "Air quality concern — renovation dust in lecture halls",
        "body": "Renovation work on the 3rd floor is generating significant dust that enters the 2nd floor lecture halls. Several students (including myself) have developed respiratory issues. Can classes be temporarily shifted or dust barriers be installed?",
        "from_name": "Mrinal Bhat",
        "from_email": "mrinal.bhat.arch3@university.ac.in",
        "status": TicketStatus.in_progress,
        "priority": Priority.medium,
        "category": Category.other,
    },
    {
        "subject": "Biometric device in examination hall not recognising my fingerprint",
        "body": "The biometric device at the entrance to the examination hall rejected my fingerprint during today's sessional test. The invigilator manually verified my ID but noted this may be flagged. Please update my biometric data to avoid issues in the final exam.",
        "from_name": "Subhash Mandal",
        "from_email": "subhash.mandal.btech2@university.ac.in",
        "status": TicketStatus.resolved,
        "priority": Priority.medium,
        "category": Category.technical_it,
    },
    {
        "subject": "Refund request for cancelled value-added course",
        "body": "I paid ₹4,500 for the 'Advanced Excel' value-added course that was cancelled by the college after only 2 sessions. It has been 45 days and the refund has not been processed. Please expedite.",
        "from_name": "Neeraj Sharma",
        "from_email": "neeraj.sharma.bcom3@college.edu.in",
        "status": TicketStatus.open,
        "priority": Priority.medium,
        "category": Category.billing_fees,
    },
    {
        "subject": "Scholarship portal shows 'Application Rejected' with no reason",
        "body": "My state scholarship application was rejected on the portal without any stated reason. I submitted all documents correctly as per the checklist. I request a review and written reason for rejection so I can appeal.",
        "from_name": "Kavitha Selvam",
        "from_email": "kavitha.s.ba2@arts.university.ac.in",
        "status": TicketStatus.in_progress,
        "priority": Priority.high,
        "category": Category.billing_fees,
    },
    {
        "subject": "Faculty absenteeism — 8 classes missed in 4 weeks",
        "body": "Prof. XYZ has been absent for 8 consecutive lectures in the Advanced Networks course over 4 weeks, with no substitute arranged. This is a core subject and the exam is in 5 weeks. I am raising this formally so it is on record.",
        "from_name": "Pavan Goud",
        "from_email": "pavan.goud.cse4@university.ac.in",
        "status": TicketStatus.open,
        "priority": Priority.high,
        "category": Category.other,
    },
    {
        "subject": "Unable to download tax invoice for income tax 80E exemption",
        "body": "I need the fee payment receipt in the specific format required for 80E income tax deduction (education loan interest). The standard receipt on the portal does not mention the interest component. Can the accounts department issue a separate certificate?",
        "from_name": "Seema Jaiswal",
        "from_email": "seema.jaiswal.mba4@bschool.ac.in",
        "status": TicketStatus.resolved,
        "priority": Priority.low,
        "category": Category.billing_fees,
    },
    {
        "subject": "Language lab headphones not working — affecting listening exam",
        "body": "20 of 30 headphones in the Language Lab are non-functional (no audio). The listening comprehension test for English Communication Skills is scheduled on June 25th. If the equipment is not fixed, the test will have to be rescheduled.",
        "from_name": "Dr. Sujata Rao",
        "from_email": "sujata.rao.english@university.ac.in",
        "status": TicketStatus.in_progress,
        "priority": Priority.high,
        "category": Category.technical_it,
    },
    {
        "subject": "Sudden removal from elective course without notification",
        "body": "I enrolled in HU-501 (Philosophy of Technology) at the start of the semester. Today I noticed I've been removed from the course on the portal without any email or notice. My assignment submitted in Week 3 is also missing. Please investigate.",
        "from_name": "Tanmay Kelkar",
        "from_email": "tanmay.k.mtech2@university.ac.in",
        "status": TicketStatus.open,
        "priority": Priority.medium,
        "category": Category.other,
    },
    {
        "subject": "Sports scholarship installment not received for March",
        "body": "I am a university kabaddi team member receiving a sports scholarship of ₹2,000/month. The March installment was not credited. April and May were credited on time. Please check the reason for the March gap.",
        "from_name": "Sudarshan Yadav",
        "from_email": "sudarshan.y.btech3@university.ac.in",
        "status": TicketStatus.resolved,
        "priority": Priority.low,
        "category": Category.billing_fees,
    },
    {
        "subject": "Hostel checkout form blocked by NOC from library",
        "body": "I am graduating and trying to complete hostel checkout. The form requires an NOC from the library. The library says I returned all books and have no dues, but they cannot generate the NOC because their system is under maintenance for 2 weeks. I leave on July 3rd.",
        "from_name": "Aishwarya Joshi",
        "from_email": "aishwarya.j.mba4@bschool.ac.in",
        "status": TicketStatus.in_progress,
        "priority": Priority.high,
        "category": Category.other,
    },
    {
        "subject": "Mobile application push notifications not working for exam alerts",
        "body": "The university mobile app sends push notifications for exam timetables and results. I haven't received any notifications since April despite turning on all app permissions on my iPhone 15. I missed an exam reschedule notification as a result.",
        "from_name": "Karishma Pillai",
        "from_email": "karishma.p.cs3@university.ac.in",
        "status": TicketStatus.open,
        "priority": Priority.medium,
        "category": Category.technical_it,
    },
    {
        "subject": "Generator not running during power cuts in examination hall",
        "body": "During the Semester 5 mid-term exam on June 19th, there was a 40-minute power cut and the DG set did not activate for 25 minutes. Students wrote in the dark. The exam time was not extended to compensate.",
        "from_name": "Abhijit Deshpande",
        "from_email": "abhijit.d.mech5@university.ac.in",
        "status": TicketStatus.resolved,
        "priority": Priority.high,
        "category": Category.other,
    },
    {
        "subject": "Wrong subject code in hall ticket",
        "body": "My hall ticket for the Semester 6 exam shows the code CS-602 for the 'Computer Networks' paper but the official timetable says CS-604. I don't know which room to report to. Please clarify and if needed reissue the hall ticket.",
        "from_name": "Harini Venkatesan",
        "from_email": "harini.v.cs6@university.ac.in",
        "status": TicketStatus.open,
        "priority": Priority.high,
        "category": Category.other,
    },
    {
        "subject": "Simulation software (MATLAB) license limit reached",
        "body": "MATLAB license shows 'Maximum concurrent users reached' every morning during lab hours. 30 students cannot proceed with their signal processing practicals. We need either more license seats or a staggered lab schedule.",
        "from_name": "Vikash Acharya",
        "from_email": "vikash.a.eee3@university.ac.in",
        "status": TicketStatus.in_progress,
        "priority": Priority.high,
        "category": Category.technical_it,
    },
    {
        "subject": "Requesting verification letter for Flipkart internship background check",
        "body": "I have accepted a summer internship at Flipkart. Their HR team requires an enrollment verification letter on official letterhead within 5 working days. Kindly issue the letter mentioning my name, course, year, and expected graduation date.",
        "from_name": "Siddharth Mahajan",
        "from_email": "siddharth.m.cs3@university.ac.in",
        "status": TicketStatus.resolved,
        "priority": Priority.medium,
        "category": Category.other,
    },
    {
        "subject": "Electricity bill being split incorrectly in shared hostel room",
        "body": "My hostel room has 3 occupants. The electricity bill is being charged equally to all 3, but one occupant has an approved AC unit which draws the majority of power. Can individual sub-meters be installed or consumption reviewed?",
        "from_name": "Sonal Daga",
        "from_email": "sonal.daga.mba3@bschool.ac.in",
        "status": TicketStatus.open,
        "priority": Priority.low,
        "category": Category.billing_fees,
    },
    {
        "subject": "Drone club equipment grant — approval pending for 3 months",
        "body": "The Drone Engineering Club submitted a proposal for ₹75,000 in equipment funding in March 2025. The proposal was approved in principle by the Technical Council but the accounts release is still pending. The inter-university drone competition is in August.",
        "from_name": "Aryan Chaturvedi",
        "from_email": "aryan.c.aero4@university.ac.in",
        "status": TicketStatus.in_progress,
        "priority": Priority.medium,
        "category": Category.billing_fees,
    },
    {
        "subject": "Migration certificate needed for GATE registration",
        "body": "I need a migration certificate from this university to register for GATE 2026. I completed my B.Tech here and am now enrolled in M.Tech at a different institute. The registrar's office says they need a request from my current university.",
        "from_name": "Praveen Reddappa",
        "from_email": "praveen.r.alumni2024@university.ac.in",
        "status": TicketStatus.open,
        "priority": Priority.medium,
        "category": Category.other,
    },
    {
        "subject": "Power bank charging station in library not working",
        "body": "The new power bank charging station installed in the library study area has been non-functional since day 1. During exam season, students rely on it. None of the 8 charging slots are working.",
        "from_name": "Chandana Menon",
        "from_email": "chandana.m.ba3@arts.university.ac.in",
        "status": TicketStatus.resolved,
        "priority": Priority.low,
        "category": Category.technical_it,
    },
    {
        "subject": "Issue with online fee payment — transaction debited twice",
        "body": "While paying my Semester 4 fees online, the page timed out and I clicked 'Pay' again. Money was deducted twice — once for ₹55,000 on June 15th and again on June 16th. Both appear in my HDFC statement. Please refund the second deduction.",
        "from_name": "Ritesh Parekh",
        "from_email": "ritesh.parekh.mca3@college.edu.in",
        "status": TicketStatus.in_progress,
        "priority": Priority.high,
        "category": Category.billing_fees,
    },
    {
        "subject": "Certificate of medium of instruction needed for UK visa",
        "body": "I have been accepted at the University of Manchester for an MSc. The UK visa requires a Certificate of Medium of Instruction confirming all teaching at this university was in English. Please issue on official letterhead with the registrar's signature.",
        "from_name": "Ishita Chakraborty",
        "from_email": "ishita.c.ba.eng4@university.ac.in",
        "status": TicketStatus.open,
        "priority": Priority.high,
        "category": Category.other,
    },
    {
        "subject": "Timetable clash — two core subjects scheduled simultaneously",
        "body": "For Semester 3 of BCA, subjects BCA-301 (Operating Systems) and BCA-305 (Computer Architecture) are scheduled on the same day at the same time (Monday, 10–11 AM, Room 201 and Room 204). This must be a timetable error.",
        "from_name": "Rohini Tawde",
        "from_email": "rohini.t.bca3@college.ac.in",
        "status": TicketStatus.resolved,
        "priority": Priority.high,
        "category": Category.other,
    },
    {
        "subject": "SQL Server connection refused in database lab",
        "body": "All workstations in DB Lab (Room 108) are unable to connect to the Microsoft SQL Server instance. Error: 'Connection to server failed — SQL Server service is not running'. The lab practical is in 2 days.",
        "from_name": "Pratap Naik",
        "from_email": "pratap.naik.bca4@college.edu.in",
        "status": TicketStatus.in_progress,
        "priority": Priority.high,
        "category": Category.technical_it,
    },
    {
        "subject": "Bus service route changed without notice — students stranded",
        "body": "The college bus on Route 7 (Borivali to Campus) changed its pickup point from Borivali Station East to Borivali Station West this week without any announcement. Around 40 students were stranded this morning. Please send a formal notice.",
        "from_name": "Shilpa Narasimhan",
        "from_email": "shilpa.n.mba2@bschool.ac.in",
        "status": TicketStatus.open,
        "priority": Priority.medium,
        "category": Category.other,
    },
    {
        "subject": "Requesting permission for overnight stay in hostel during semester break",
        "body": "I have a national level hackathon at IIT Bombay from July 7–8. I need to stay in my hostel room the night before (July 6th) even though the official semester break has started. The hostel warden has asked for a formal request.",
        "from_name": "Sushant Garg",
        "from_email": "sushant.garg.cs4@university.ac.in",
        "status": TicketStatus.resolved,
        "priority": Priority.low,
        "category": Category.other,
    },
    {
        "subject": "Separate OBC non-creamy layer scholarship not applied",
        "body": "I fall under OBC Non-Creamy Layer category. The state government's OBC scholarship (separate from NSP) requires an institutional application. I submitted the form in February. The accounts office has not forwarded it to the state directorate yet.",
        "from_name": "Omkar Waghmare",
        "from_email": "omkar.w.btech3@university.ac.in",
        "status": TicketStatus.open,
        "priority": Priority.high,
        "category": Category.billing_fees,
    },
    {
        "subject": "Research stipend not paid for 2 months — PhD scholar",
        "body": "I am a JRF-funded PhD scholar. My CSIR-NET research stipend (channelled through the university) has not been credited for April and May 2025. Total pending: ₹62,000. I depend on this as my only income.",
        "from_name": "Dr. Archana Kulkarni",
        "from_email": "archana.k.phd@research.university.ac.in",
        "status": TicketStatus.in_progress,
        "priority": Priority.high,
        "category": Category.billing_fees,
    },
    {
        "subject": "Smart classroom interactive board not calibrated correctly",
        "body": "The touch calibration on the smart board in Room 301 is off by approximately 10 cm. When I tap a point, the cursor appears 10 cm to the right. This makes it unusable for teaching. Lab assistant has tried re-calibrating without success.",
        "from_name": "Prof. Santosh Kulkarni",
        "from_email": "santosh.kulkarni.maths@university.ac.in",
        "status": TicketStatus.resolved,
        "priority": Priority.medium,
        "category": Category.technical_it,
    },
    {
        "subject": "CGPA recalculation needed after grade correction",
        "body": "My grade in CS-401 was corrected from C to B+ after a revaluation last month. However, my CGPA on the portal still reflects the old grade. The corrected CGPA should be 7.91 instead of 7.64. This affects my placement eligibility.",
        "from_name": "Nilesh Raut",
        "from_email": "nilesh.raut.cs4@university.ac.in",
        "status": TicketStatus.open,
        "priority": Priority.high,
        "category": Category.other,
    },
    {
        "subject": "International student (NRI) requesting local bank account NOC",
        "body": "I am an NRI student from Dubai enrolled in the B.Com programme. I need an NOC on university letterhead confirming my student status so I can open a resident Indian savings account with SBI for receiving my father's remittances.",
        "from_name": "Zaid Hamdan",
        "from_email": "zaid.hamdan.nri.bcom2@university.ac.in",
        "status": TicketStatus.resolved,
        "priority": Priority.medium,
        "category": Category.other,
    },
    {
        "subject": "Online fee calculator showing incorrect late fee amount",
        "body": "The fee calculator on the portal says the late fee is ₹100/day beyond the deadline. The official fee structure document (attached) says ₹50/day. Multiple students will be overcharged if the portal is not corrected before the deadline.",
        "from_name": "Poornima Rajan",
        "from_email": "poornima.r.btech3@university.ac.in",
        "status": TicketStatus.in_progress,
        "priority": Priority.medium,
        "category": Category.billing_fees,
    },
    {
        "subject": "Cannot register for electives — prerequisites not recognised",
        "body": "I completed CS-301 (Data Structures) last semester with an A grade but the system is blocking me from registering for CS-501 (Algorithms) citing 'Prerequisite CS-301 not fulfilled'. The grades are in my transcript. Please fix this manually.",
        "from_name": "Dhruv Agrawal",
        "from_email": "dhruv.agrawal.cs4@university.ac.in",
        "status": TicketStatus.open,
        "priority": Priority.medium,
        "category": Category.technical_it,
    },
    {
        "subject": "Waste management complaint — garbage not collected for 4 days",
        "body": "Garbage from the student hostel area (Blocks A–D) has not been collected for 4 days. The overflowing bins are attracting stray animals and causing a hygiene hazard. Please alert campus maintenance.",
        "from_name": "Varsha Negi",
        "from_email": "varsha.negi.hostel@university.edu.in",
        "status": TicketStatus.resolved,
        "priority": Priority.medium,
        "category": Category.other,
    },
]

random.seed(42)

now = datetime.now(timezone.utc)

def random_date(days_back: int) -> datetime:
    offset = timedelta(
        days=random.randint(0, days_back),
        hours=random.randint(0, 23),
        minutes=random.randint(0, 59),
    )
    return now - offset


def main():
    with Session(engine) as session:
        existing = session.query(Ticket).count()
        if existing > 0:
            print(f"Found {existing} existing tickets — deleting them first.")
            session.query(Ticket).delete()
            session.commit()

        for i, t in enumerate(TICKETS):
            created = random_date(180)
            ticket = Ticket(
                id=str(uuid.uuid4()),
                subject=t["subject"],
                body=t["body"],
                status=t["status"],
                priority=t["priority"],
                category=t["category"],
                from_email=t["from_email"],
                from_name=t.get("from_name"),
                thread_id=f"thread-{uuid.uuid4()}",
                assignee_id=random.choice(AGENT_IDS + [None, None]),
                created_at=created,
                updated_at=created + timedelta(hours=random.randint(0, 48)),
            )
            session.add(ticket)

        session.commit()
        print(f"Seeded {len(TICKETS)} tickets successfully.")


if __name__ == "__main__":
    main()
